# Generated by Django 5.2.7 on 2026-04-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_fw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='code',
            field=models.CharField(default='user_default', max_length=50, unique=True, verbose_name='ユーザーコード'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='favorite_food',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='好きな食べ物'),
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('status', models.CharField(choices=[('NOT_STARTED', '未着手'), ('IN_PROGRESS', '進行中'), ('COMPLETED', '完了')], default='NOT_STARTED', max_length=20, verbose_name='ステータス')),
                ('priority', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高')], default='MEDIUM', max_length=20, verbose_name='優先度')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='_fw.projectmodel', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='アサイン日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='_fw.usermodel', verbose_name='ユーザー')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='_fw.taskmodel', verbose_name='タスク')),
            ],
            options={
                'verbose_name': 'タスクアサイン',
                'verbose_name_plural': 'タスクアサイン',
                'db_table': 'task_assignments',
                'unique_together': {('task', 'user')},
            },
        ),
    ]
